version: '3'
services:
  graph:
    build:
      context: ./graph
      dockerfile: ./dev/Dockerfile
    volumes: 
      - ./graph:/app/go
    ports:
      - 90:80
    tty: true
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
    hostname: mysql
    ports: 
      - "3307:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - ./docker/dev/db/conf.d:/etc/mysql/conf.d
      - ./docker/dev/db/log/mysql:/var/log/mysql
volumes:
  db-data:
    driver: local