version: '3'
services:
  vue:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    volumes:
    - .:/app
    # command: sh -c "cd /app/react  && yarn start"
    ports:
      - 8080:8080
  go:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    volumes: 
      - .:/app
    ports:
      - 3000:3000
    tty: true
  # nginx:
  #   image: nginx
  #   depends_on:
  #     - go
  #   ports:
  #     - 80:80
  #   environment:
  #     - TZ=Asia/Tokyo
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf